# Generated by Django 4.2.13 on 2024-05-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="first_name",),
        migrations.RemoveField(model_name="order", name="surname",),
        migrations.RemoveField(model_name="order", name="title",),
        migrations.AddField(
            model_name="order",
            name="full_name",
            field=models.CharField(max_length=254, null=True),
        ),
    ]
