# Generated by Django 4.2.13 on 2024-05-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_remove_order_first_name_remove_order_surname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="original_basket",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_pid",
            field=models.CharField(default="", max_length=254),
        ),
    ]
