# Generated by Django 4.2.13 on 2024-08-12 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0004_product_organic"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_code", models.CharField(editable=False, max_length=32)),
                (
                    "stars",
                    models.CharField(
                        choices=[
                            (0, "None"),
                            (1, "Poor"),
                            (2, "Ok"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=1000, null=True)),
                ("name", models.CharField(blank=True, max_length=254, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.userprofile",
                    ),
                ),
            ],
        ),
    ]
