# Generated by Django 4.2.13 on 2024-08-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="stars",
            field=models.CharField(
                choices=[
                    (0, "None"),
                    (1, "Poor"),
                    (2, "Ok"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default="0",
                max_length=1,
            ),
        ),
    ]
