# Generated by Django 4.2.13 on 2024-05-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20240508_1930"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product", options={"verbose_name_plural": "Products"},
        ),
        migrations.AlterField(
            model_name="category",
            name="friendly_name",
            field=models.CharField(default="Product Category", max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="friendly_name",
            field=models.CharField(default="Store Product", max_length=200),
        ),
    ]
