# Generated by Django 4.2.13 on 2024-05-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_alter_product_options_alter_category_friendly_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="organic",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
